
services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: <Your PostgreSQL Connection String>
      - key: JWT_SECRET
        value: <Your Secret Key>
